import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import QueryProvider from './providers';
import ContentProvider from './(content)/provider';

export interface RootLayoutProps {
  children: React.ReactNode;
}

const font = Manrope({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Read Journey',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${font.className} p-[20px] antialiased`}>
        <QueryProvider>
          <ContentProvider>{children}</ContentProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
