import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';

const font = Manrope({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Read Journey',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} p-[20px] antialiased`}>
        {children}
      </body>
    </html>
  );
}
